from sc2.constants import *




PERFECT_MACRO = [
    HATCHERY,  # 1
    OVERLORD,  # 1
    DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE,  # 12
    DRONE,  # 13
    OVERLORD,  # 2
    DRONE,  # 14
    DRONE,  # 15
    DRONE,  # 16
    HATCHERY,  # 2 (First expand)
    DRONE,  # 17
    EXTRACTOR,  # 1
    SPAWNINGPOOL,
    DRONE, DRONE, DRONE, # 20
    OVERLORD,  # 3
    QUEEN,  # 1
    ZERGLING,  # 1
    ZERGLING,  # 2
    QUEEN,  # 2
    DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE,  # 28
    OVERLORD,  # 4
    DRONE, DRONE, DRONE, DRONE, DRONE,  # 33
    HATCHERY,
    DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE,  # 40
    OVERLORD,  # 5
    DRONE, DRONE,  # 47
    OVERLORD,  # 6
]

TWO_BASE_LING_RUSH = [
    HATCHERY,  # 1
    OVERLORD,  # 1
    DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE,  # 12
    DRONE,  # 13
    OVERLORD,  # 2
    DRONE,  # 14
    DRONE,  # 15
    DRONE,  # 16
    DRONE,  # 17
    DRONE,  # 18
    HATCHERY,  # 2 (First expand)
    DRONE,  # 19
    EXTRACTOR,  # 1
    SPAWNINGPOOL,
    DRONE, DRONE, DRONE,  # 22
    OVERLORD,  # 3
    ZERGLINGMOVEMENTSPEED,  # 1
    QUEEN,  # 1
    ZERGLING,  # 1
    ZERGLING,  # 2
    QUEEN,  # 2
    DRONE, DRONE, DRONE, DRONE, DRONE, DRONE, DRONE,  # 30
    OVERLORD,  # 4
    BANELINGNEST,  # 1
    EXTRACTOR,  # 2
]
TWO_BASE_LING_RUSH += ([OVERLORD] + [ZERGLING] * 14 + [BANELING] * 1) * 1  # BUILD FORCES
TWO_BASE_LING_RUSH += [LAIR]
TWO_BASE_LING_RUSH += ([OVERLORD] + [ZERGLING] * 12 + [BANELING] * 3) * 1  # BUILD FORCES
TWO_BASE_LING_RUSH += [CENTRIFICALHOOKS]
TWO_BASE_LING_RUSH += ([OVERLORD] + [ZERGLING] * 9 + [BANELING] * 6) * 7  # BUILD FORCES
